yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.PostHome.as_view(), name="index"),
    path("group/<slug:slug>/", views.GroupPosts.as_view(), name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.csrf_failure"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

# from django.db.models import Q

User = get_user_model()


class Group(models.Model):
    title = models.CharField("Наименование", max_length=200)
    slug = models.SlugField("Адрес", unique=True, null=True)
    description = models.TextField("Описание")

    class Meta:
        verbose_name = "Группa"
        verbose_name_plural = "Группы"

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        "Текст поста",
        help_text="Введите текст поста",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Автор",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Выберите группу",
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        "Картинка",
        upload_to="posts/",
        blank=True,
        help_text="Добавьте картинку",
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    class Meta:
        ordering = (
            "-created",
            "-pk",
        )
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Комментируемый пост",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Автор",
    )
    text = models.TextField(
        "Текст комментария",
        help_text="Напишите комментарий",
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self) -> str:
        return self.text[:20]


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Избранный автор",
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_relationships"
            ),
            models.CheckConstraint(
                name="prevent_self_follow",
                check=~models.Q(user=models.F("author")),
            ),
        ]

    def __str__(self) -> str:
        return f"{self.user} подписан на {self.author}"

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )

    def clean_text(self):
        data = self.cleaned_data["text"]
        if not data:
            raise forms.ValidationError()

        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

POST_PER_PAGE = 10


class PostHome(ListView):
    """Главная страница."""

    paginate_by = POST_PER_PAGE
    model = Post
    template_name = "posts/index.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.all()


class GroupPosts(ListView):
    """Страница группы."""

    paginate_by = POST_PER_PAGE
    model = Group
    template_name = "posts/group_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        group = get_object_or_404(Group, slug=self.kwargs["slug"])
        return Post.objects.filter(group=group)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = str(context["posts"][0].group)
        context["description"] = context["posts"][0].group.description
        return context


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """Страница профиля."""
    author = get_object_or_404(User, username=username)
    posts_author = author.posts.all()
    following = author.following.all().exists()
    paginator = Paginator(posts_author, POST_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    template = "posts/profile.html"
    context = {
        "author": author,
        "posts_author": posts_author,
        "page_obj": page_obj,
        "following": following,
    }
    return render(request, template, context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Страница записи."""
    post_info = get_object_or_404(Post, pk=post_id)
    author_post = post_info.author_id
    count_author_posts = (
        Post.objects.select_related("author")
        .filter(author_id=author_post)
        .count()
    )
    comments = post_info.comments.all()
    form = CommentForm()
    template = "posts/post_detail.html"
    context = {
        "post_info": post_info,
        "count_author_posts": count_author_posts,
        "form": form,
        "comments": comments,
    }
    return render(request, template, context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Создание нового поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == "POST" and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author.username)

    template = "posts/create_post.html"
    context = {
        "form": form,
    }
    return render(request, template, context)


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    """Редактирование поста."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=post.pk)

    template = "posts/create_post.html"
    context = {
        "post": post,
        "form": form,
        "is_edit": True,
    }
    return render(request, template, context)


@login_required
def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    template = "posts:post_detail"
    return redirect(template, post_id=post.pk)


@login_required
def follow_index(request: HttpRequest) -> HttpResponse:
    """
    Страница всех постов авторов, на которых подписан текущий пользователь.
    """
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, POST_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    template = "posts/follow.html"
    context = {
        "page_obj": page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request: HttpRequest, username: str) -> HttpResponse:
    # Подписаться на автора
    current_user = request.user
    author = get_object_or_404(User, username=username)
    if author != current_user:
        Follow.objects.get_or_create(user=current_user, author=author)
        return redirect("posts:profile", username=username)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request: HttpRequest, username: str) -> HttpResponse:
    # Дизлайк, отписка
    current_user = request.user
    Follow.objects.filter(
        user=current_user, author__username=username
    ).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %} 
{% if is_edit %}
    <title>Редактировать запись</title>
{% else %}
<title>Добавить запись</title>
{% endif %} 
{% endblock %} 

{%block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} 
            Редактировать пост 
            {% else %} 
            Новый пост 
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %} 
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  {{field.label}}                
                  {% if field.field.required %}
                  <span class="required text-danger" >*</span>{% endif %}                  
                </label>
                {{ field }}              
                <small id="id_text-help" class="form-text text-muted">
                  {{ field.help_text}}
                </small>
              </div>
            {% endfor %}
                <p>
                  {{ form.errors }}
                  {% if form.errors %}
                    {% for field in form %}
                      {% for error in field.errors %}            
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endif %}
                </p>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} 
                   Сохранить 
                  {% else %} 
                   Добавить 
                   {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %} 
{% block title %}
<title>Лента постов избранных авторов</title>
{% endblock %} 
{% block header %}Лента постов избранных авторов{% endblock %}
{%block content %}
<div class="container">
<h1>Лента постов избранных авторов</h1>
<main>
  {% include "posts/includes/switcher.html" %}
  {% for post in page_obj %} 
  {% include "posts/includes/post_list.html" %} 
  {% if not forloop.last %}
  <hr />
  {% endif %} 
  {% endfor %} 
   {% include "posts/includes/paginator.html" %}
</div>
</main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}
  <title> {{ title }}</title>
{% endblock %} 
{% block content %}
<div class="container">
 <h1> {{ title }} </h1>
  <main>
    <p>{{ description }}</p>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>Дата публикации: {{ post.created|date:"d E Y" }}</li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        <article>
        <a href="{% url 'posts:post_detail' post.pk %}">
          подробная информация
        </a>
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %} 
      {% endfor %}
      <!-- если записей больше 10 -- подключён паджинатор -->
      {% include "posts/includes/paginator.html" %}
      </hr>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %} 
{% load cache %} 
{% block title %}
<title>Последние обновления на сайте</title>
{% endblock %} 
{% block header %}Последние обновления на сайте{% endblock %}
{%block content %}
<div class="container">
<h1>Последние обновления на сайте</h1>
<main>
  {% cache 20 index_page page_obj.number %} 
  {% include "posts/includes/switcher.html" %}
  {% for post in page_obj %} 
  {% include "posts/includes/post_list.html" %} 
  {% if not forloop.last %}
  <hr />
  {% endif %} 
  {% endfor %} 
  {% endcache %}
   {% include "posts/includes/paginator.html" %}
</div>
</main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title> {{ post_info|truncatechars:30 }} </title>
{% endblock %} {% block content %}
<main>
  <div class="container">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post_info.created|date:"d E Y" }}
        </li>
        {% if post_info.group %}
        <li class="list-group-item">
          Группа: {{ post_info.group.title }}
          <a href="{% url 'posts:group_list' post_info.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post_info.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between 
          align-items-center">
          Всего постов автора: 
          <span>{{ count_author_posts }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_info.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_info.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post_info.text|linebreaksbr }}</p>
      <!-- эта кнопка видна только автору -->
      {% if user == post_info.author %}
      <a class="btn btn-primary"
        href="{% url 'posts:post_edit' post_info.pk %}">
        редактировать запись
      </a>
      {% endif %}
      {% include "posts/includes/comment.html" %}
    </article>
  </div>
</div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    <title>Профайл пользователя {{ author.get_full_name }}</title>
{% endblock %}
{% block content %}
<div class="container">
<main>
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_author.count }} </h3> 
        {% if following %}
         <a class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" 
          role="button">Отписаться
         </a>
        {% else %}
          <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" 
            role="button"> Подписаться
         </a>
        {% endif %}
        {% for posts_author in page_obj %}
        <article>
          <ul>
            <li>
              Дата публикации: {{ posts_author.created|date:"d E Y" }} 
            </li>
            {% if posts_author.group %}
              <li> 
                Группа: {{ posts_author.group }} 
                <a href="{% url 'posts:group_list' posts_author.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
          </ul>
          {% thumbnail posts_author.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p> {{ posts_author.text|linebreaksbr }} </p>
          <a href="{% url 'posts:post_detail' posts_author.pk %}">
            подробная информация
          </a>
        </article>
        {% if not forloop.last %} 
        <hr>
        {% endif %} 
        {% endfor %}
        <!-- если записей больше 10 -- подключён паджинатор -->
        {% if posts_author.count > 10 %}
         {% include "posts/includes/paginator.html" %}
        {% endif %}
        </hr>
      </div>
    </main>
{% endblock %}